feat: Enhance pre-commit hook and add DashboardHeader tests

diff --git a/.husky/pre-commit b/.husky/pre-commit
--- a/.husky/pre-commit
+++ b/.husky/pre-commit
@@ -1,5 +1,13 @@
+#!/bin/sh
+. "$(dirname "$0")/_/husky.sh"
+
 echo 'Check for linting errors and run tests before commiting...'
 
 npx lint-staged || (echo 'Liting erros or tests failed. Please fix them before commiting.' && exit 1)
+
+npm test || {
+  echo 'Unit tests failed. Please fix them before committing.'
+  exit 1
+}
 
 echo 'Check done!'
